### ISSUE TITLE
Mouse Cursor Invisible

### ISSUE THREAD

**Issue by bendparker** [rdesktop/rdesktop#86]
I am running RPi 3, and rdesktop 1.8.2, connecting to Windows Server 2012 R2.  Upon connection the mouse pointer becomes invisible.  The "disable pointer shadow" does not work.  I've tried to manually set the pointer to something else and that doesn't work either.  It's either always invisible, or it's stuck on the black line text selection cursor.

I apologize if this has been fixed, but I've tried all the fixes listed and nothing has worked.

**Comment by hean01-cendio** [comment]
Do you know which bitdepth the X server is using ?

Could you try run rdesktop with '-a 32' argument to see if that matters ?

**Comment by bendparker** [comment]
Yes I will try this.

**Comment by bendparker** [comment]
Some more information:  I changed from full screen mode to a slightly less than full screen (-g 1900 x 1040) and this helped a bit.  The mouse pointer stayed, but now seems to be intermittently disappearing.  Trying the -a 32 and will report back.

**Comment by bendparker** [comment]
I tried the suggested fix and it did not work.  A little more info, the mouse cursor seems to disappear when typing an email (or any other larger text box) and then never returns.

**Comment by jhudsoncedaron** [comment]
Sounds like the same bug that caused me to add -M on my branch to not accept remote mouse cursors.

**Comment by bendparker** [comment]
Does it work for you?  If so I can try your branch?  Or can I just add -M to my script on the main branch?

**Comment by bendparker** [comment]
I have actually relegated this to a particular user's profile.  If I do the exact same connection with another user, it works fine.

**Comment by jhudsoncedaron** [comment]
-M does not exist on the main branch. My branch is here: https://github.com/joshudson/rdesktop

**Comment by hean01-cendio** [comment]
Could it bew related to mouse cursor themes that includes alpha which rdesktop can't render ? If it works with another one user profile but not a second ?

**Comment by bendparker** [comment]
I think it has to do with some weird graphic settings that he uses.  He likes the text and such to appear larger than they really are.

**Comment by hean01-cendio** [comment]
Nice hints, then we have something to go on. Is he using high dpi mode eg. scaling of everything within his session ?

**Comment by bendparker** [comment]
Yes.  The "Make Text appear larger" option within view properties.

**Comment by jhudsoncedaron** [comment]
That would also explain why I can't not encounter it. I must use high DPI.

**Comment by dad68** [comment]
@bendparker 
(sorry for my English....)
I have exactly the same problem as you. But only on the windows  login page. After login  i have no problems. 
I tried many ideas on the forums, but I found no solution.
Did you found a solution ?

I use:
Rdesktop with a Raspberry PI3
The distant is : W10 on a wmware

**Comment by jhudsoncedaron** [comment]
@dad68 Pull my branch https://www.github.com/joshudson/rdesktop and pass -M to the version of rdesktop built from there. Poof. Gone.

**Comment by dad68** [comment]
Thank you but I do not understand what banche you are referring to.*
Sorry I'm a little beginner

Currently i start rdesktop with this command line : rdesktop -U
utilisateur -D domaine -k fr 192.168.... -f

Thanks


2017-02-28 17:17 GMT+01:00 jhudsoncedaron <notifications@github.com>:

**Comment by dad68** [comment]
Thank you but I do not understand what banche you are referring to.*
Sorry I'm a little beginner

Currently i start rdesktop with this command line : rdesktop -U utilisateur -D domaine -k fr 192.168.... -f

Thanks

**Comment by hean01-cendio** [comment]
I have dug inte the cursor issue in rdesktop. The thing is that rdesktop have code to parse cursor sent from server, however rdesktop uses XCreatePixmapCursor which only support 2 colors cursors fg and bg color and a mask. Due to this restriction in XCreatePixmapCursor, there is code that converts the cursor into 2 colors cursors. This is the reason for all the cursors problems in rdesktop, I have a lab branch offline which uses XRender extension which support RGBA cursors which fixes this cursor problem but raises the requirments of XRender.

**Comment by hean01-cendio** [comment]
Commit 6dd85ed rewrites the cursor code and now supports color cursors and alpha.

**Comment by joshudson** [comment]
![rdp-cursor-notfixed](https://user-images.githubusercontent.com/16249210/30777892-860bce6e-a07a-11e7-936a-9cdb4ef16cef.png)

Cursor still doesn't show. Should be a white I-beam but it's a black I-beam which is barely visible at all.

**Comment by hean01-cendio** [comment]
@joshudson ah ok, That problem is due to X cursors doens't support xor pixels in cursors, so i had to choose black pixels for those. A solution to this is to add a white outline and the the beam would be visibible on both black and white backgrounds.

**Comment by hean01-cendio** [comment]
@joshudson , What I found is that the caret cursor is the only one with xor pixels, all the other cursors should look ok. Could you confirm that this is the case for you eg. problem is only related to the caret cursor when background of text input fields are black.

**Comment by hean01-cendio** [comment]
Commit 0954ac3 adds outlined rendering of XOR cursors which solves this problem.

**Comment by seidler2547** [comment]
Adding `-x 0xA0` solved the problem for me. I'll leave this comment here so that people who can't run the latest version can work around this issue.

**Comment by uglym8** [comment]
Just to clarify this magic value (**0xA0**): 
it's **PERF_DISABLE_CURSOR_SHADOW | PERF_ENABLE_FONT_SMOOTHING** 

Reference:
https://msdn.microsoft.com/en-us/library/cc240476.aspx

**Comment by hean01-cendio** [comment]
@uglym8 that solution is a known problem that was resolved with the new mouse rendering code that supports alpha...

**Comment by uglym8** [comment]
yep, @hean01-cendio, I'm aware of that:)
Just wanted to demistify this value.

**Comment by anthonysymons** [comment]
I am still having problems with the mouse cursor, even on the current release.

I gather from the above the issue it is related to available hardware cursor colour options on my workstation, and the remote machine. I keep checking back in with rdesktop as other than this issue, and unfortunate blocker for people with some kind of hardware, it works really well. I have built above version with the -M switch and use that as a work around.  It'd be great if that patch could end up in an official release as it is a valuable workaround for people with one of the remaining cursor issues.

It sounds like the code is good now and the issue for me is just a compatibility thing, but some kind of work around is still required.

**Comment by CendioOssman** [comment]
Note that the fix referenced above is **not** in 1.8.6. It will be in 1.9.0 though.

**Comment by syadnom** [comment]
Any solution here for 1.8.6?

**Comment by ausinch** [comment]
When you RDP to a Windows 10 PC ensure your Windows mouse size setting is at 1.
Any other size will cause problems.
![Selection_028](https://user-images.githubusercontent.com/16511860/70796223-fd031800-1da1-11ea-917f-be982d6ebba6.png)

**Comment by VeNoMouS** [comment]
```
   -M: use local mouse cursor
```

**Comment by HTM-Alan** [comment]
> Adding `-x 0xA0` solved the problem for me. I'll leave this comment here so that people who can't run the latest version can work around this issue.

This solved it for me Windows server 2012 r2

SESSION_0_RDESKTOP_OPTIONS="-u '' -d seudominio -a 16 -f -k 416 -k en-us -x 0xA0

I'm still trying on Windows server 2019 version

**Comment by tpetersonkth** [comment]
> This fixed it for me...
> 
> ```
>    -M: use local mouse cursor
> ```
> 
> Where as... `-x 0xA0` and `-g 32` did nothing...

This solved my problem(Adding -M)! For me, the mouse cursor was disappearing when hovering over text fields(F.e notepad.exe).

**Comment by steelman** [comment]
> When you RDP to a Windows 10 PC ensure your Windows mouse size setting is at 1. Any other size will cause problems. 

It was exactly opposite for me. Setting size to 2 made the white cursor stop disappearing over text fields. Interestingly enough the black one (middle) of size 1 works fine.

**Comment by maduranma** [comment]
> > This fixed it for me...
> > ```
> >    -M: use local mouse cursor
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Where as... `-x 0xA0` and `-g 32` did nothing...
> 
> This solved my problem(Adding -M)! For me, the mouse cursor was disappearing when hovering over text fields(F.e notepad.exe).

I'm still having the same problem of cursor disappearing on text fields, I guess maybe because some property of it, transparency or whatever, the only solution is either -M (but I don't like it as you always get the arrow) or making the cursor bigger in Windows settings.
I don't know why this happens but I remote connect to my work computer and I program in there so this is a little bit annoying
